name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-node: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # Этот скрипт создаст базовую оболочку для твоего HTML
          npx @bubblewrap/cli init --manifest=https://raimaslanov222.github.io/Beasblox/manifest.json --yes
          npx @bubblewrap/cli build --yes

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Beasblox-Release-APK
          path: ./*.apk
          
